# Generated by Django 6.0.1 on 2026-02-11 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_is_verified_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otptoken',
            name='url_code',
            field=models.CharField(default='a4582b', max_length=6),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='114549', max_length=6),
        ),
    ]
