# Generated by Django 6.0.1 on 2026-02-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_otptoken_url_code_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='e5e14f', max_length=6),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='url_code',
            field=models.CharField(default='9de8f8', max_length=6),
        ),
    ]
