# Generated by Django 6.0.1 on 2026-02-22 19:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_otptoken_otp_code_alter_otptoken_url_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='1526f0', max_length=6),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_expires_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 2, 22, 20, 14, 20, 214359, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='url_code',
            field=models.CharField(default='a164ab', max_length=6),
        ),
    ]
