# Generated by Django 6.0.1 on 2026-02-25 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_otptoken_otp_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otptoken',
            name='url_code',
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='c1891c', max_length=6),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_expires_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 2, 25, 12, 42, 14, 519506, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
