# Generated by Django 6.0.1 on 2026-03-09 00:17

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_otptoken_url_code_alter_otptoken_otp_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='a3850e', max_length=6),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_expires_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 3, 9, 0, 37, 59, 305719, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.CreateModel(
            name='UrlCodeOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_code', models.CharField(default='34da046026fa3a8baeeaa3b22774001f', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, default=datetime.datetime(2026, 3, 9, 0, 22, 59, 306015, tzinfo=datetime.timezone.utc), null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
