# Generated by Django 6.0.1 on 2026-03-15 03:30

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_otptoken_otp_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default=users.models.generate_opt_token, max_length=6),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_expires_at',
            field=models.DateTimeField(blank=True, default=users.models.get_default_expires_OptToken, null=True),
        ),
        migrations.AlterField(
            model_name='urlcodeotp',
            name='expires_at',
            field=models.DateTimeField(blank=True, default=users.models.get_default_expires_UrlCodeOtp, null=True),
        ),
        migrations.AlterField(
            model_name='urlcodeotp',
            name='url_code',
            field=models.CharField(default=users.models.generate_url_code_opt, max_length=32),
        ),
    ]
